version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend

  backend:
    build: ./sample-data-backend
    container_name: backend
    ports:
      - "4000:4000"